### ISSUE TITLE
Deciding on UI Framework or library

### ISSUE THREAD

**Issue by rajasimha1991** [airavata-courses/TeamSangam#1]
AngularJS will be a good option to consider. As we are building application in a distributed environment, I think AngularJS will complement that scalable architecture.

**Comment by ramarvab** [comment]
Spring cannot be used  because it's tough to scale and it spends most of the time waiting for IO. Other framework which i thought is play which is scalable and has non blocking IO. Play is mostly written is scala, so it may take a little learning curve to implement in play.I am not sure about node.js. Even we can use react but its new and user community is not  so good.

So we can go with either angularjs or play which are easily scalable.

**Comment by vikaspro90** [comment]
Good points @ramarvab ... But I too prefer Angular above others... Apart from what @rajasimha1991 has said, Angular is easy to start with as we are not too acquainted with front-end frameworks. The online community is pretty huge and it is widely used in the industry. As far as the backend for login and signup service is concerned, I am thinking of using python with Flask. Lightweight yet robust. I prefer Python over Javascript(on NodeJS) for backend. Its just that it is better to use a backend language for backend purposes and I hate the inconsistencies in Javascript. Let me know what you guys think.

**Comment by rajasimha1991** [comment]
Finally we are using AngularJS library to build the UI
