### ISSUE TITLE
Accessing Environment Variables in EC2

### ISSUE THREAD

**Issue by ramarvab** [airavata-courses/TeamSangam#23]
Our Approach : 

We wrote a script in before_script block of .travis.yml file for saving the secure environment variables into a .properties file and  access those values in after_install script under hook of  appspec.yml

Issue: During the execution of after_install script, it is unable to find the .properties file.
But I am able to see the file at the end of deployment. It looks like this is a racing condition.

Is there a work around for this or another approach to pass the secure values via environment variables to our application in EC2.

**Comment by gouravshenoy** [comment]
The problem I feel is that your "before_script" block is a part of travis, and "after_install" is a part of CodeDeploy. They have 2 separate contexts - travis has its own execution environment, whereas codedeploy runs on your EC2 instance. 
Whatever you create in any part of travis will not be accessible during codedeploy deployments simply because they are running in different environments altogether.

**Comment by praddyinstant** [comment]
I completely understand that. But my understanding is that CodeDeploy starts only after Travis builds the Application bundle and sends it to the AWS S3. The after_install scripts are part of that bundle and when that is executing, I assumed the files will also be accessible.
Note: I am able to view the file when I login to EC2 instance.

**Comment by vikaspro90** [comment]
Don't see this issue now. This most likely occurred due to a confusion between afterInstall and Install phases of the deployment. Closing.
